# This workflow will build and deploy the angular application

name: Build and deploy Angular application

description: This workflow will build and deploy the Angular application into the given repository in GitHub

#Inputs for the action script
inputs:
  source_dir:
    description: The directory where the distribution bundle is located, e.g., dist/app-name
    required: true
  
  target_repo:
    description: The repository where the distribution bundle will be deployed
    required: true
  
  target_branch:
    description: The branch inside the 'target-repo' where the distribution bundle will be deployed. Defaults to "main" branch.
    required: false
    default: main
  
  user_email:
    description: Email for git-push
    required: true
  
  user_name:
    description: GitHub username for git-push
    required: true
  
  commit_message:
    description: Custom commit message for git-commit
    required: false
    default: Commit

# Run configuration for the action script
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.source_dir }}
    - ${{ inputs.target_repo }}
    - ${{ inputs.target_branch }}
    - ${{ inputs.user_email }}
    - ${{ inputs.user_name }}
    - ${{ inputs.commit_message }}

branding:
  icon: play-circle
  color: blue
